name: PowerShell Universal Bug report 🐛
description: Create a bug report for PowerShell Universal
labels: PowerShell Universal,bug,requires triage
body:
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of PowerShell Universal are you running?
    options:
      - 3.8.9
      - 3.8.8
      - 3.8.7
      - 3.8.6
      - 3.8.5
      - 3.7.14
      - 3.7.13
      - 3.7.12
      - 3.7.11
      - 3.7.10
      - 2.12.6
      - 2.12.5
      - 2.12.4
      - Other Please Specify
  validations:
    required: true
- type: dropdown
  id: impact
  attributes:
    label: Impact
    description: How severly is this bug impacting you? 
    options:
      - Low
      - High
      - Critical
      - Visual Defect
      - Missing Content
  validations:
    required: true
- type: textarea
  attributes:
   label: Steps to Reproduce
   description: > 
      List of steps, sample code, failing test or link to a project that reproduces the behavior.
      Make sure you place a stack trace inside a code (```) block to avoid linking unrelated issues.
   placeholder: >
      I am experiencing a problem with X.
      I think Y should be happening but Z is actually happening.
  validations:
     required: true
- type: textarea
  attributes:
    label: Expected behavior
    render: console
    placeholder: |
      PS> 2 + 2
      4
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behavior
    render: console
    placeholder: |
      PS> 2 + 2
      5
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment data
    description: Please include information about your environment. 
    placeholder: > 
      Version Number (If not selected above):
      Dashboard Framework (if applicable): 
      Operating System: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Visuals
    description: >
      Please upload images or animations that can be used to reproduce issues in the area below.
      Try the [Steps Recorder](https://support.microsoft.com/en-us/windows/record-steps-to-reproduce-a-problem-46582a9b-620f-2e36-00c9-04e25d784e47)
      on Windows or [Screenshot](https://support.apple.com/en-us/HT208721) on macOS.
