name: PowerShell Universal v5 Beta Feedback
description: Feedback on the v5 beta. 
labels: PowerShell Universal,v5-beta
body:
- type: textarea
  attributes:
    label: Summary of the feedback
    description: >
      Please supply an issue you are experiencing or a feature you would like see implemented. Consider a discussion if it makes more sense. See the discussion tab above.  
  validations:
    required: true
